# example netlify.toml
[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200
  
[[redirects]]
  from = "/index.html"
  to = "/index.html"
  status = 200
  [[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "/experiments.html"
  to = "/experiments.html"
  status = 200

    [[redirects]]
  from = "/about.html"
  to = "/about.html"
  status = 200
